# -*- coding: utf-8 -*-
"""ml test 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1571-ywDJ9R-YkIhFp84ZI4jmwSg4C4Tj
"""

import numpy as np
import scipy as sc
import matplotlib.pyplot as plt
from sklearn.datasets import load_boston

boston = load_boston()

print (boston.DESCR)

"""formula de minimos cuadrados Ordinario simplificada 
MCO 

---


$\beta =(X^{T}X)^{-1}X^{T}Y$
"""

X = np.array(boston.data[:,5])
Xdata = X
Y = np.array(boston.target)

plt.scatter(X,Y,alpha= 0.3)

X = np.array([np.ones(506),X]).T

B = np.linalg.inv(X.T @ X) @X.T @Y
B

plt.plot([4,9],[B[0]+B[1]*4,B[0]+B[1]*9 ],c = "red")

plt.scatter(Xdata,Y,alpha= 0.3)
plt.show()